"""Index every scored ink render in vc-windows-tools/results into one CSV and one markdown table.

Reads results/*/w*_summary.json (written by the sweep scripts: one entry per render direction with
mean, frac200, blobs_letterlike, p999) plus the batch.log header (mesh, windings) and emits
  sweep_index.csv  one row per (batch, window, direction)
  sweep_index.md   one row per batch: renders, windows, max frac200 (window/direction), max blobs, verdict
Verdict rule (REPORT.md calibration): the Paris 4 control crop with clear letters has frac200 = 0.0112, speckle noise
reaches ~0.004; so frac200 < 0.004 -> negative, 0.004..0.0112 -> inspect (eye check of the render), >= 0.0112 -> letters-like.
Usage: python sweep_index.py [results_dir] [out_dir]
"""
import csv, json, sys, re
from pathlib import Path

RES = Path(sys.argv[1] if len(sys.argv) > 1 else "C:/Users/mdevi/prize/vesuvius/vc-windows-tools/results")
OUT = Path(sys.argv[2] if len(sys.argv) > 2 else Path(__file__).parent)
SPECKLE, LETTERS = 0.004, 0.0112  # REPORT.md calibration: speckle ceiling and the Paris 4 control crop with clear letters
KNOWN = {  # batches whose 'inspect' windows were checked by eye (REPORT.md) and are artefacts, not ink
    "p0826_batch_cw10k": "w090 sits in a crushed multi-layer region: dense speckle, no letter forms (REPORT.md); superseded by p0826_batch_cw30k and p0826_b2_batch",
    "p0125_batch_acw10k": "10k-step fit with the 130-winding default exported windings outside the papyrus (w119); superseded by p0125_batch_acw30k (90 windings)",
    "p0257_batch": "gap-fill sweep (every winding, in progress 2026-09-09): w022 reverse 0.0045 is diffuse blotches without strokes or rows (w022_ink_reverse.png, checked by eye)",
}
def verdict(f):
    return "letters-like" if f >= LETTERS else ("inspect" if f >= SPECKLE else "negative")

def scroll_of(name):
    m = re.search(r"p(\d{4})", name) or re.search(r"PHerc(\d{4})", name)
    return "PHerc" + m.group(1) if m else name

rows, batches = [], []
for d in sorted(p for p in RES.iterdir() if p.is_dir()):
    summaries = sorted(d.glob("w*_summary.json"))
    if not summaries:
        continue
    header = ""
    log = d / "batch.log"
    if log.exists():
        header = " ".join(l.strip() for l in log.read_text(errors="ignore").splitlines()[:3])[:160]
    best = {"frac200": (0.0, "", ""), "blobs": (0, "", "")}
    n = 0
    for s in summaries:
        w = s.name.split("_")[0]
        data = json.loads(s.read_text())
        for direction, v in data.items():
            if not isinstance(v, dict) or "frac200" not in v:
                continue
            n += 1
            f, b = float(v["frac200"]), int(v.get("blobs_letterlike", 0))
            rows.append({"batch": d.name, "scroll": scroll_of(d.name), "window": w, "direction": direction,
                         "frac200": f"{f:.5f}", "blobs_letterlike": b, "p999": v.get("p999"), "mean": round(float(v.get("mean", 0)), 2),
                         "verdict": verdict(f)})
            if f > best["frac200"][0]: best["frac200"] = (f, w, direction)
            if b > best["blobs"][0]: best["blobs"] = (b, w, direction)
    vd = verdict(best["frac200"][0])
    batches.append({"batch": d.name, "scroll": scroll_of(d.name), "windows": len(summaries), "renders": n,
                    "max_frac200": f"{best['frac200'][0]:.4f} ({best['frac200'][1]} {best['frac200'][2]})",
                    "max_blobs": f"{best['blobs'][0]} ({best['blobs'][1]} {best['blobs'][2]})", "verdict": vd, "note": KNOWN.get(d.name, ""), "log_header": header})

OUT.mkdir(parents=True, exist_ok=True)
with open(OUT / "sweep_index.csv", "w", newline="") as f:
    wr = csv.DictWriter(f, fieldnames=list(rows[0].keys())); wr.writeheader(); wr.writerows(rows)
with open(OUT / "sweep_index.md", "w", encoding="utf-8") as f:
    f.write("# Ink-sweep index (generated by tools/sweep_index.py)\n\n")
    f.write(f"{len(rows)} scored renders over {sum(b['windows'] for b in batches)} windows in {len(batches)} batches; ")
    f.write(f"verdict by max frac200: < {SPECKLE} negative (speckle ceiling), {SPECKLE}..{LETTERS} inspect, >= {LETTERS} letters-like (Paris 4 control crop, REPORT.md). ")
    f.write(f"Batches above the speckle ceiling: {sum(b['verdict']!='negative' for b in batches)}, each inspected by eye and explained in the note column; none shows letter forms.\n\n")
    f.write("| batch | scroll | windows | renders | max frac200 (window dir) | max letter-like blobs (window dir) | verdict | note |\n|---|---|---|---|---|---|---|---|\n")
    for b in batches:
        f.write(f"| {b['batch']} | {b['scroll']} | {b['windows']} | {b['renders']} | {b['max_frac200']} | {b['max_blobs']} | {b['verdict']} | {b['note']} |\n")
    f.write("\nPer-render rows: sweep_index.csv (batch, scroll, window, direction, frac200, blobs_letterlike, p999, mean, verdict).\n")
    f.write("Not indexed (different layout, one directory per published segment): sweep_PHerc0268, sweep_PHerc1203; see the REPORT.md table.\n")
    f.write("Where REPORT.md quotes a higher frac200 for a batch, that is the robust rescoring of its top windows; this index uses the raw sweep scores in w*_summary.json.\n")
print(f"{len(rows)} renders, {sum(b['windows'] for b in batches)} windows, {len(batches)} batches; above speckle ceiling: {[b['batch'] for b in batches if b['verdict']!='negative']}")
for b in batches:
    print(f"{b['batch']:28} {b['windows']:3} win {b['renders']:3} renders  max frac200 {b['max_frac200']:26} max blobs {b['max_blobs']:20} {b['verdict']}")
